### PR TITLE
added dark theme css, options, and injection javascript

### LINKED ISSUE #243: Add dark theme.
Could you add dark theme please.

### PR DESCRIPTION
**Pull request by bhhaskin**
First attempt at adding a dark theme based off Firefox's dark theme.

Added dark-theme CSS.
Check box option in the options page.
Added dark icon SVGs.

The CSS just overrides colors, border colors and SVG backgrounds.
SVG Icons are the same as the originals but with different color fills and strokes.

This resolves #243

### CODE REVIEW

**Comment by bhhaskin** [comment]
Injecting the style sheet isn't great, but I couldn't see a way to do it with mithril.js

**Comment by maximbaz** [comment]
Huge thanks for looking into it @bhhaskin, I want to use the dark theme myself 🙂 

Just to let you know, we are in the middle of developing a next major version of browserpass, which is a complete rewrite and has a bit different design. We had a pause recently, but planning to resume the work soon. Not every feature is ported yet, so the markup and design is still changing. Let me ping you once the UI stabilizes so that you can rebase your improvement on the v2.

**Comment by bhhaskin** [comment]
@maximbaz  sure thing! Thanks!

**Comment by maximbaz** [comment]
@bhhaskin thanks again for the PR, we have settled on the following design in v3, it has been merged and will be part of the next release.

image

**Comment by bhhaskin** [comment]
Awesome! It looks fantastic!

**Pull request closed without merging**
